<?php

/**
* Class Funcionarios generated by Chrysalis v.1.0.0
* 
* Chrysalis info:
* @author pabhoz
* github: @pabhoz
* bitbucket: @pabhoz
* 
*/ 
 
class Funcionarios extends BModel {

    private $id;
    private $nome;
    private $email;
    private $cpf;
    private $data_nasc;
    private $obs;
    private $user_id;

    public function __construct( $id,  string $nome, string $email, string $cpf, string $data_nasc, string $obs, int $user_id) {

        parent::__construct();
        $this->id = $id;
        $this->nome = $nome;
        $this->email = $email;
        $this->cpf = $cpf;
        $this->data_nasc = $data_nasc;
        $this->obs = $obs;
        $this->user_id = $user_id;
    }

    public function getId(): int {
        return $this->id;
    }

    public function getNome(): string {
        return $this->nome;
    }

    public function getEmail(): string {
        return $this->email;
    }

    public function getCpf(): string {
        return $this->cpf;
    }

    public function getData_nasc(): string {
        return $this->data_nasc;
    }

    public function getObs(): string {
        return $this->obs;
    }

    public function getUser_id(): int {
        return $this->user_id;
    }

    public function setId(int $id) {
        $this->id = $id;
    }

    public function setNome(string $nome) {
        $this->nome = $nome;
    }

    public function setEmail(string $email) {
        $this->email = $email;
    }

    public function setCpf(string $cpf) {
        $this->cpf = $cpf;
    }

    public function setData_nasc(string $data_nasc) {
        $this->data_nasc = $data_nasc;
    }

    public function setObs(string $obs) {
        $this->obs = $obs;
    }

    public function setUser_id(int $user_id) {
        $this->user_id = $user_id;
    }

    public function getMyVars(){
        return get_object_vars($this);
    }

}