<?php

/**
* Class Pedidos generated by Chrysalis v.1.0.0
* 
* Chrysalis info:
* @author pabhoz
* github: @pabhoz
* bitbucket: @pabhoz
* 
*/ 
 
class Pedidos extends BModel {

    private $id;
    private $cliente_id;
    private $funcionario_id;
    private $produto_id;
    private $user_id;
    private $data;
    private $quantidade;
    private $preco;

    public function __construct( $id,  int $cliente_id, int $funcionario_id, int $produto_id, int $user_id, string $data, int $quantidade, string $preco) {

        parent::__construct();
        $this->id = $id;
        $this->cliente_id = $cliente_id;
        $this->funcionario_id = $funcionario_id;
        $this->produto_id = $produto_id;
        $this->user_id = $user_id;
        $this->data = $data;
        $this->quantidade = $quantidade;
        $this->preco = $preco;
    }

    public function getId(): int {
        return $this->id;
    }

    public function getCliente_id(): int {
        return $this->cliente_id;
    }

    public function getFuncionario_id(): int {
        return $this->funcionario_id;
    }

    public function getProduto_id(): int {
        return $this->produto_id;
    }

    public function getUser_id(): int {
        return $this->user_id;
    }

    public function getData(): string {
        return $this->data;
    }

    public function getQuantidade(): int {
        return $this->quantidade;
    }

    public function getPreco(): string {
        return $this->preco;
    }

    public function setId(int $id) {
        $this->id = $id;
    }

    public function setCliente_id(int $cliente_id) {
        $this->cliente_id = $cliente_id;
    }

    public function setFuncionario_id(int $funcionario_id) {
        $this->funcionario_id = $funcionario_id;
    }

    public function setProduto_id(int $produto_id) {
        $this->produto_id = $produto_id;
    }

    public function setUser_id(int $user_id) {
        $this->user_id = $user_id;
    }

    public function setData(string $data) {
        $this->data = $data;
    }

    public function setQuantidade(int $quantidade) {
        $this->quantidade = $quantidade;
    }

    public function setPreco(string $preco) {
        $this->preco = $preco;
    }

    public function getMyVars(){
        return get_object_vars($this);
    }

}