<?php

/**
* Class Produtos generated by Chrysalis v.1.0.0
* 
* Chrysalis info:
* @author pabhoz
* github: @pabhoz
* bitbucket: @pabhoz
* 
*/ 
 
class Produtos extends BModel {

    private $id;
    private $descricao;
    private $unidade;
    private $data_cadastro;
    private $user_id;

    public function __construct( $id,  string $descricao, string $unidade, string $data_cadastro, int $user_id) {

        parent::__construct();
        $this->id = $id;
        $this->descricao = $descricao;
        $this->unidade = $unidade;
        $this->data_cadastro = $data_cadastro;
        $this->user_id = $user_id;
    }

    public function getId(): int {
        return $this->id;
    }

    public function getDescricao(): string {
        return $this->descricao;
    }

    public function getUnidade(): string {
        return $this->unidade;
    }

    public function getData_cadastro(): string {
        return $this->data_cadastro;
    }

    public function getUser_id(): int {
        return $this->user_id;
    }

    public function setId(int $id) {
        $this->id = $id;
    }

    public function setDescricao(string $descricao) {
        $this->descricao = $descricao;
    }

    public function setUnidade(string $unidade) {
        $this->unidade = $unidade;
    }

    public function setData_cadastro(string $data_cadastro) {
        $this->data_cadastro = $data_cadastro;
    }

    public function setUser_id(int $user_id) {
        $this->user_id = $user_id;
    }

    public function getMyVars(){
        return get_object_vars($this);
    }

}